Cap america
Tarto-4/First-Capstone pull request #1
Opened 2023-05-31 12:16 UTC by Tarto-4

## Capstone Pull Request
- Added a functional .html file
- Uploaded background images and social icons
- Added a .css file for webpage styling 
- The added script file contains web features
- Configured linters packages
- Updated README file

2023-05-31 12:27 UTC, levy002 reviewed
## Hello @Tarto-4  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request :x: :x: 

You have submitted a project, that doesn't have a professional README file.

- [ ] Kindly make sure to include all main sections from the [Microverse README template](https://github.com/microverseinc/readme-template) which will help to explain your repository contents and have a clean and professional Readme. Please make sure to customize it according to your project and fill in the needed information and remember all main sections must be included except the FAQ section which is optional.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-31 12:41 UTC, Tarto-4 commented
Thank you for the feedback. I have updated my read me file as instructed.

2023-05-31 13:25 UTC, BregornOriginal requested changes
Hi @Tarto-4  

Good job so far!

There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

![cat-driving-serious](https://github.com/Tarto-4/First-Capstone/assets/93630700/b98adeca-3d16-405b-96de-2645cbabfa35)

## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-05-31 13:25 UTC, BregornOriginal commented on README.md
> +### Deployment
Good job updating your README file 💯 

- Kindly as was requested, deploy your application on GitHub Pages and add the link to this section

2023-05-31 13:25 UTC, BregornOriginal commented on index.html
> +    <footer class="bottom" id="updates">
- [x] Good work implementing the footer. To follow the same layout in the Behance design, kindly align the text to the right and the logo to the left

- [x] As we can see the footer is bigger on the Behance design, kindly add more padding to your footer on both pages

- [x] Kindly make the background in your `Desktop version white on your home page`

Footer on desktop version home page

![image](https://github.com/Tarto-4/First-Capstone/assets/93630700/14b90955-9f38-47de-a276-db2370a8f4f4)

Footer on the desktop version of the page

![image](https://github.com/Tarto-4/First-Capstone/assets/93630700/a9654ba1-d719-4819-b08f-e088c379bf14)

2023-05-31 13:25 UTC, BregornOriginal commented on about.html
> +    <footer class="bottom">
- [x] Good work implementing the footer. To follow the same layout in the Behance design, kindly align the text to the right and the logo to the left

2023-05-31 13:25 UTC, BregornOriginal commented on index.html
> +            <div class="program-container container">
Good job implementing the `Main Program` section. To match better with the Behance design 

- [ ] Kindly reduce the gap between each card

- [ ] Change the font-family text in this section for `Lato`

- [ ] Reduce the size of your description text

- [ ] And lastly, as you can see the card container is centered in the middle of the section. You could reduce the space between the cards and the section to center it in the middle, maybe adjusting the size of the container or using margins.

![image](https://github.com/Tarto-4/First-Capstone/assets/93630700/67dc0126-249d-4b43-96d7-946356db1536)

![image](https://github.com/Tarto-4/First-Capstone/assets/93630700/ac6b767b-3ce1-4252-9dc4-851406d3975d)

2023-05-31 13:25 UTC, BregornOriginal commented on index.html
> +        <section class="first-speaker">
Excellent work implementing dynamically your Featured Speakers section 💯 

There are some changes to make here to make this a better match with Behances design

- [ ] I can see that your font-size is too big for this section and maybe that it's using all the space on the cards, maybe you can reduce it a bit to use the space for each element

- [ ] Kindly fix the size of the images to have the same size between them. I've seen that you are giving a size in the properties, but maybe the image is different in your assets.

- [ ] As we can see, here the font-family used is `Lato`, kindly implement it

- [ ] There's a bit more space between the grey line and the subtitle and description, kindly add this missing space


![image](https://github.com/Tarto-4/First-Capstone/assets/93630700/0110e9e6-d656-41cd-a66d-926b833fad54)

![image](https://github.com/Tarto-4/First-Capstone/assets/93630700/af3fad02-4035-4b13-a1d4-9f31f8f6f45d)

2023-05-31 13:25 UTC, BregornOriginal commented on index.html
> +    <nav class="mobile-nav">
Good work implementing the hamburger button! 💯 It works properly

- [ ] To match the Behance design, kindly add a bit more space between the button and the borders

![image](https://github.com/Tarto-4/First-Capstone/assets/93630700/efb077a3-bca2-439a-966a-5915772c379b)

2023-05-31 13:25 UTC, BregornOriginal commented on style.css
> +  .program-container {
In your program container, there are some changes to make

- [ ] Reducing the size of your font in this section will give you more space in the cards to work and will match also Behance design

- [ ] Kindly align the description of the text to match the rest of the cards

- [ ] Here there's a Lato font family too in the design

![image](https://github.com/Tarto-4/First-Capstone/assets/93630700/9acb9160-00bd-4e70-aab5-27cab717a225)

![image](https://github.com/Tarto-4/First-Capstone/assets/93630700/f3c72def-a140-470c-9ce6-1b5cf0e88ee7)

2023-06-01 14:43 UTC, amejid approved these changes
Hi @Tarto-4, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/RltjLEzzB87ErJdxHz/giphy.gif"/>

## Highlights
- Linter checks passing :heavy_check_mark: 
- Correct workflow :heavy_check_mark: 
- Good UI design :heavy_check_mark: 
- Changes implemented :heavy_check_mark: 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-01 14:44 UTC, merged